version: "3.9"

services:

  acms:
    container_name: acms
    image: smartairkey/acmsuae:late
    restart: always
    networks:
      - dev-stage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`devacms.airkey.ae`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=le"
      - "traefik.http.routers.whoami.tls.options=whoami@file"
    logging:
      driver: "elastic/elastic-logging-plugin:7.10.2"
      options:
        hosts: "http://93.159.221.89:9200"
        index: "acms-dev-ae-%{+yyyy.MM.dd}"

networks:
  dev-stage:
    name: dev-stage
    driver: bridge