version: "3.9"

services:

  acms:
    container_name: acms-dev
    image: smartairkey/acms-dev:late
    restart: always
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.acms.entrypoints=https
      - traefik.http.routers.acms.rule=Host(`devacms.smartairkey.com`)
      - traefik.http.routers.acms.service=origin-web
      - traefik.http.services.origin-web.loadbalancer.server.port=80
      - traefik.http.routers.acms.tls=true
      - traefik.http.routers.acms.tls.certresolver=le
    logging:
      driver: "elastic/elastic-logging-plugin:7.10.2"
      options:
        hosts: "http://157.175.156.105:9200"
        index: "acms-dev-rf-%{+yyyy.MM.dd}"
    networks:
      - test-stage
      - keyserver

  traefik:
    container_name: traefik
    image: traefik:v2.5.3
    ports:
      - 443:443/tcp
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.https.address=:443
      - --certificatesresolvers.le.acme.email=admin@airkey.ae
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.le.acme.httpChallenge.entryPoint=http
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/letsencrypt:/letsencrypt
      - /opt/traefik_tls.yml:/configs/traefik_tls.yml
    restart: unless-stopped
    networks:
      - keyserver

networks:
  test-stage:
    name: test-stage
    driver: bridge
  keyserver:
  