server {
    listen 80 default_server;
    server_name  _ ;
    index index.html;
    root /acms/dist; 
    location = / {
      return 301 $scheme://$http_host/ru/intercom/;
    }

    location /ru/ {
       alias /acms/dist/ru/;
       try_files $uri $uri/ /ru/index.html;
       add_header Cache-Control public;
    }  

    location /en/ {
       alias /app/dist/en/;
       try_files $uri $uri/ /en/index.html;
       add_header Cache-Control public;
    }  
}












