server {
    listen 80 default_server;
    server_name  _ ;
    root /acms/dist/intercom/;
    location / {
      try_files $uri $uri/ /index-ru.html;
    }
   location /ru/intercom {
      alias /acms/dist/intercom;
      try_files $uri $uri/ /index-ru.html;
  
   }
   location /en/intercom {
      alias /acms/dist/intercom;
      try_files $uri $uri/ /index-en.html;

   }
   location ~* (.*admin/) {
      alias /acms/dist/admin;
      try_files $uri $uri/ /index-ru.html;

   }
   
}











