server {
    listen 80 default_server;
    server_name  _ ;
     root /usr/share/nginx/html;
     index index.html;

   location /ru/intercom {
      alias /acms/dist/intercom;
      index index-ru.html;
      try_files $uri $uri/ /index-ru.html;
  
   }
   location /en/intercom {
      alias /acms/dist/intercom;
      index index-en.html;
      try_files $uri $uri/ /index-en.html;

   }
   location /ru/admin {
      alias /acms/dist/admin;
      index index-ru.html;
      try_files $uri $uri/ /index-ru.html;

   }
   location /en/admin {
      alias /acms/dist/admin;
      index index-ru.html;
      try_files $uri $uri/ /index-ru.html;

   }


   
}











